name: Build My-Carton App

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: write

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Run Build Script
        shell: cmd
        run: |
          call run.bat

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ./artefacts
            ./deploy/installer
            ./deploy/client

  release:
  name: Release My-Carton
  runs-on: ubuntu-22.04
  needs: run-script
  if: startsWith(github.ref, 'refs/tags/')

  permissions:
    contents: write

  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: release_files

    - name: Debug structure
      run: |
        echo "=== FULL TREE ==="
        find release_files

    - name: Prepare release files (flatten)
      run: |
        mkdir -p release_upload

        # беремо ВСІ файли (не тільки exe)
        find release_files -type f -exec cp {} release_upload/ \;

        echo "=== FINAL RELEASE FILES ==="
        ls -R release_upload

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG="${{ github.ref_name }}"

        echo "Creating release for $TAG"

        FILES=$(find release_upload -type f)

        gh release create "$TAG" \
          --repo "$GITHUB_REPOSITORY" \
          --title "My-Carton $TAG" \
          --generate-notes \
          $FILES